# Интерфейсы scikit-learn

In [1]:
from sklearn.base import BaseEstimator, TransformerMixin, OneToOneFeatureMixin
from sklearn.metrics import r2_score
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
from numpy.typing import NDArray
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [2]:
import yaml

with open('../config.yaml', 'r') as f:
    cfg = yaml.safe_load(f)

## Estimator

Для примера построим простой estimator, который в перспективе будет вычитать из признаков их среднее значение и после сдвигать признаки на заранее заданную константу

In [3]:
class SubtractMeanAndShiftEstimator(BaseEstimator):
    def __init__(self, shift=0.):
        self.shift: float = shift
        self.means_: NDArray = None  # we add a trailing underscore for parameters which will be learnt in fit()

    def fit(self, X: NDArray, y: NDArray = None):
        # y is ignored here
        self.means_ = X.mean(axis=0)  # the first axis corresponds to samples by default
        return self

In [4]:
m = SubtractMeanAndShiftEstimator(shift=3)

Метод `get_params()` реализован в `BaseEstimator`, и мы можем сразу использовать его для получения гиперпараметров модели. Это возможно, так как единственный гиперпараметр `shift` был передан как явное ключевое слово в контрукторе

Обратите внимание, что соответствующий аттрибут класса должен совпадать с ключевым словом: `self.shift = shift`

In [5]:
m.get_params()

{'shift': 3}

Аналогично мы можем использовать `set_params()` для задания значений гиперпараметров. Этот метод пригодится при поиске оптимальных значений гиперпараметров

In [6]:
m.set_params(shift=5)
m.get_params()

{'shift': 5}

In [7]:
X = np.array([
    [1, 10],
    [3, 30],
    [2, 20],
])
y = np.array([
    [ 0, -8],
    [ 2, 10],
    [ 1,  1],
])
m.fit(X, y)

SubtractMeanAndShiftEstimator(shift=5)

В sklearn есть класс sklearn.base.OutlierMixin, который позволяет реализовывать кастомные классы для определения выбросов.
Он добавляет:
- атрибут _estimator_type, по умолчанию outlier_detector
- fit_predict.

Метод fit() работает в формате без учителя, predict же должен классифицировать данные на аутлаеры (возвращать для них -1) и обыычные данные (возвращать 1). Для классификации используется отсечка по порогу предсказаний, полученных внутренним.
Во встроенных методах функция оценки доступна с помощью метода `score_samples`, в то время как порог можно задать параметром `contamination`. 
Например, для гауссовских данных можно использовать sklearn.covariance.EllipticEnvelope.

**Задание**: Создайте свой эстиматор с использованием sklearn.base.OutlierMixin, который будет определять выбросы на основе интерквартильного размаха. 
Он должен возвращать один столбец с 1 и -1, а также позволять задавать порог для квантиля, определяющего размах. Не забудьте, что он должен быть двухсторонним.
Ваш эстиматор должен работать и для датафреймов, и для numpy массивов.

In [8]:
from sklearn.base import BaseEstimator, OutlierMixin
class MyEstimator(BaseEstimator, OutlierMixin):
     def __init__(self,factor=1.5):
        self.factor = factor
     def fit(self, X, y=None):
         self.is_fitted_ = True
         X = pd.DataFrame(X.copy())
         q1 = X.quantile(0.35)
         q3 = X.quantile(0.55)
         iqr = q3 - q1
         self._lower_bound = q1 - (self.factor * iqr)
         self._upper_bound = q3 + (self.factor * iqr)
         print(X.min(axis=0))
         return self
         
     def predict(self, X):
         temp = np.ones(len(X))
         temp[(X > self._lower_bound.values).all(axis=1) & (X < self._upper_bound.values).all(axis=1)] = -1
         return temp


In [9]:
estimator = MyEstimator()
true_cov = np.array([[.8, .3],
                     [.3, .4]])
X = np.random.RandomState(42).multivariate_normal(mean=[0, 0],
                                                 cov=true_cov,
                                                 size=500)
e = estimator.fit(X)
#pred = estimator.predict(X)
e._lower_bound

0   -2.918998
1   -1.876028
dtype: float64


0   -0.934051
1   -0.820153
dtype: float64

In [10]:
e._upper_bound

0    0.712770
1    0.677671
dtype: float64

In [11]:
e.predict(X)

array([-1., -1., -1.,  1., -1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,
        1., -1.,  1., -1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1., -1.,
       -1.,  1.,  1., -1., -1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,
        1., -1.,  1.,  1., -1., -1., -1., -1., -1., -1., -1.,  1., -1.,
       -1.,  1., -1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1., -1.,
        1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1., -1., -1., -1., -1.,
        1.,  1.,  1.,  1., -1.,  1., -1.,  1., -1., -1., -1.,  1., -1.,
        1., -1., -1.,  1., -1., -1., -1.,  1., -1., -1.,  1.,  1., -1.,
        1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1., -1., -1., -1.,
        1.,  1., -1., -1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,
        1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1.,
       -1., -1., -1., -1., -1., -1., -1.,  1., -1., -1.,  1., -1., -1.,
       -1.,  1., -1., -1., -1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.,
       -1., -1., -1., -1.,  1., -1., -1., -1., -1., -1., -1., -1

## Predictor

Рассмотрим тот же класс, но добавим к нему методы `predict()` и `score()`

In [12]:
class SubtractMeanAndShiftPredictor(BaseEstimator):
    def __init__(self, shift=0.):
        self.shift: float = shift
        self.means_: NDArray = None  # we add a trailing underscore for parameters which will be learnt in fit()

    def fit(self, X: NDArray, y: NDArray = None):
        # y is ignored here
        self.means_ = X.mean(axis=0)  # the first axis corresponds to samples by default
        return self

    def predict(self, X: NDArray) -> NDArray:
        e = np.ones((X.shape[0], 1))
        return X -  e @ self.means_.reshape(-1, 1).T + self.shift

    def score(self, X: NDArray, y: NDArray) -> float:
        return r2_score(y, self.predict(X))  # R2 \in (-\infty; 1] is the coefficient of determination

Так как мы специально добавили небольшое отклонение в y, наш R2 чуть меньше 1

In [13]:
model = SubtractMeanAndShiftPredictor(shift=1)
model.fit(X)
model.predict(X)
model.score(X, y)

ValueError: Found input variables with inconsistent numbers of samples: [3, 500]

## Transformer

Рассмотрим тот же класс, но добавим к нему метод `transform()`

In [14]:
class SubtractMeanAndShiftTransformer(BaseEstimator, OneToOneFeatureMixin, TransformerMixin):
    def __init__(self, shift=0.):
        self.shift: float = shift
        self.means_: NDArray = None  # we add a trailing underscore for parameters which will be learnt in fit()

    def fit(self, X: NDArray, y: NDArray = None):
        # y is ignored here
        self.means_ = X.mean(axis=0)  # the first axis corresponds to samples by default
        return self

    def transform(self, X: NDArray) -> NDArray:
        e = np.ones((X.shape[0], 1))
        return X -  e @ self.means_.reshape(-1, 1).T + self.shift

In [15]:
t = SubtractMeanAndShiftTransformer(shift=5)
t.fit(X)
t.transform(X)

array([[4.61391607, 4.69717723],
       [4.09987339, 5.34409129],
       [5.26760315, 4.99381043],
       [3.46939606, 4.58731335],
       [5.29161135, 5.43772751],
       [5.5191865 , 4.99991932],
       [5.24389177, 4.04919283],
       [6.63155718, 5.5416523 ],
       [5.81384802, 5.59050612],
       [6.12193465, 4.79715004],
       [3.79685518, 4.21133018],
       [5.28182267, 4.34062904],
       [5.45600327, 5.28614781],
       [5.91904706, 5.68091218],
       [5.59757666, 5.13846277],
       [5.10346764, 6.06393206],
       [5.26709066, 4.53645106],
       [4.58232403, 4.07943612],
       [5.28320388, 4.04448556],
       [6.11345348, 5.68570059],
       [4.33352263, 4.71896187],
       [5.18066387, 4.91011528],
       [6.45502286, 5.35972974],
       [5.1651667 , 5.65563936],
       [5.12136006, 4.06699938],
       [4.82007666, 4.67052659],
       [5.45491051, 5.56348222],
       [3.90528209, 4.91152698],
       [5.80778018, 5.24123741],
       [4.49971111, 5.25422289],
       [5.

Так как мы добавили `TransformerMixin`, мы можем использовать метод `fit_transform()`, не реализуя его явно

In [16]:
t.fit_transform(X)

array([[4.61391607, 4.69717723],
       [4.09987339, 5.34409129],
       [5.26760315, 4.99381043],
       [3.46939606, 4.58731335],
       [5.29161135, 5.43772751],
       [5.5191865 , 4.99991932],
       [5.24389177, 4.04919283],
       [6.63155718, 5.5416523 ],
       [5.81384802, 5.59050612],
       [6.12193465, 4.79715004],
       [3.79685518, 4.21133018],
       [5.28182267, 4.34062904],
       [5.45600327, 5.28614781],
       [5.91904706, 5.68091218],
       [5.59757666, 5.13846277],
       [5.10346764, 6.06393206],
       [5.26709066, 4.53645106],
       [4.58232403, 4.07943612],
       [5.28320388, 4.04448556],
       [6.11345348, 5.68570059],
       [4.33352263, 4.71896187],
       [5.18066387, 4.91011528],
       [6.45502286, 5.35972974],
       [5.1651667 , 5.65563936],
       [5.12136006, 4.06699938],
       [4.82007666, 4.67052659],
       [5.45491051, 5.56348222],
       [3.90528209, 4.91152698],
       [5.80778018, 5.24123741],
       [4.49971111, 5.25422289],
       [5.

Аналогично мы можем использовать метод `get_feature_names_out()`, так как мы добавили `OneToOneFeatureMixin`

In [17]:
t.get_feature_names_out(input_features=['x', 'y'])

NotFittedError: This SubtractMeanAndShiftTransformer instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
Используем датасет с домами как пример. Вспомним, что мы делали в прошлый раз, и попробуем заполнить пропущенные значения в некоторых числовызх столбцах.
Для этого используем трансформер по столбцам. 


In [18]:
df = pd.read_csv(cfg['house_pricing']['train_dataset'])
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\data\\spbu_ai_fundamentals\\house_prices\\train.csv'

По умолчанию, только указанные столбцы трансформируются и возвращаются (remainder=`drop`). Мы же сделаем так, чтобы все остальные столбцы тоже возвращались, просто с ними бы ничего не делалось. 

In [ ]:
ct = ColumnTransformer(
    [('mean_impute', SimpleImputer(strategy='mean'), ['SalePrice', 'LotArea', 'WoodDeckSF',  'MasVnrArea'])], 
    remainder="passthrough")

ct.fit(df)

In [ ]:
ct.transform(df)

In [ ]:
ct.set_output(transform='pandas')

Если у датасета появятсся столбцы, которые не были представлены во время fit (даже среди тех, что не трансформировались), то они будут выкинуты на этапе transform. 

In [ ]:
df["temp"] = 0
ct.transform(df)

**Задание**: Перейдите к медианному заполнению пропусков. Проверьте, что результаты, полученные с помощью трансформации, соответствуют преобразованию напрямую.

**Задание**: Добавьте еще нормализатор для LotFrontage, LotArea и запустите в ColumnTransformer. Обучите его и примените.

Sklearn располагает большим количеством встроенных трансформеров. Соответствующие трансформеры есть и для категориальных фичей (более подробно рассмотрим этот тип чуть позже). Например, известное нам бинарное кодирование можно проводить с помощью OneHotEncoder()

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(
    transformers=[
        ('median_impute', SimpleImputer(strategy='mean'), ['SalePrice', 'LotArea', 'WoodDeckSF',  'MasVnrArea']),
        ("one_hot_encode", OneHotEncoder(handle_unknown="ignore", sparse_output=False), ["MSZoning", "SaleType", "SaleCondition"]),
    ], 
    remainder="passthrough")

ct.fit(df)

In [ ]:
ct.set_output(transform='pandas')
ct.transform(df)

Для выбора столбцов можно создавать make_selector, например, по выбору численных и категориальных значений. 

**Доп. задание**. Сделайте трансформер для OneHotEncoder на основе make_selector так, чтобы выбирать все нечисловые столбцы. Сколько столбцов получается после трансформации?

In [ ]:
from sklearn.compose import make_column_selector as selector

# Your code

## Pipelines

С помощью Pipeline мы можем производить последовательную обработку данных и выполнять предсказание в конце

In [ ]:
X = np.array([
    [1, 10],
    [3, 30],
    [2, 20],
])
y = np.array([
    [0],
    [2],
    [1],
])

pipeline = Pipeline([
    ("shifter", SubtractMeanAndShiftTransformer(shift=5)),
    ("regressor", LinearRegression()),
])
...
pipeline.fit(X, y)
y_pred = pipeline.predict(X)
print(y_pred)

Pipeline хранит последовательные Estimators в аттрибуте `steps`

In [ ]:
pipeline.steps

Перейти к объекту i-го Estimator можно напрямую через `pipeline[i]`:

In [ ]:
pipeline[0]

In [ ]:
pipeline[1].coef_

Так как Pipeline сам является Estimator, мы можем увидеть список его параметров:

In [ ]:
pipeline.get_params()

Видно, параметры промежуточных Estimator указаны как `<estimator>__<parameter>`. Следовательно, мы можем изменить параметры любого промежуточного Estimator:

In [ ]:
pipeline.set_params(shifter__shift=10)
pipeline.get_params()

In [ ]:
**Задание**: Создайте пайплайн по преобразованию чсиленных столбцов, содержащий импьютер и скейлер.

**Задание**: Создайте новый трансформер, который для категориальных столбцов будет заполнять пропущенные значения наиболее часто встречаюмшщимся или новой категорией (сделайте параметром). 

**Задание**: Создайте пайплайн по преобразованию категориальных столбцов, содержащий ваш импьютер и OneHotEncoder.

**Задание**: Создайте ColumnTransformer, который будет содержать в себе два вышеуказанных пайплайна.

**Доп.задание**: Используйте для комбинации результатов двух отдельных трансформеров FeatureUnion